# Generated by Django 4.2 on 2024-04-25 16:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import multiselectfield.db.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('about', models.TextField(max_length=200, verbose_name='about')),
                ('about_en', models.TextField(max_length=200, null=True, verbose_name='about')),
                ('about_es', models.TextField(max_length=200, null=True, verbose_name='about')),
                ('name', models.CharField(max_length=200, verbose_name='Name')),
                ('email', models.EmailField(max_length=200, verbose_name='Email')),
                ('phone', models.CharField(max_length=20, null=True, verbose_name='Phone')),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Title')),
                ('service_type', models.CharField(choices=[('Family Fun', 'Family Fun'), ('Health and Well-being', 'Health and Well-being'), ('Benefits or Financial Aid', 'Benefits or Financial Aid')], max_length=200, verbose_name='Type of Event')),
                ('description', models.TextField(max_length=200, verbose_name='Description')),
                ('age_group', multiselectfield.db.fields.MultiSelectField(choices=[('0y', '0-1 years'), ('1y', '1-2 years'), ('2y', '2-3 years'), ('3y', '3-4 years'), ('4y', '4-5 years'), ('5y', '5-6 years'), ('6y', '6-7 years'), ('7y', '7-8 years'), ('8y', '8-9 years'), ('9y', '9-10 years'), ('10y', '10-11 years'), ('11y', '11-12 years'), ('12y', '12-13 year'), ('13+', '13 or older'), ('P', 'For Parents'), ('All', 'All ages')], max_length=25, verbose_name='Age Group')),
                ('location', models.CharField(blank=True, max_length=200, null=True, verbose_name='Location')),
                ('start_date', models.DateField(blank=True, null=True, verbose_name='Start Date')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='End Date')),
                ('price', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Price')),
                ('organization', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='parent_resource_app.organization')),
            ],
        ),
    ]
