# Generated by Django 4.2 on 2024-04-25 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parent_resource_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='eventtranslation',
            name='end_date',
        ),
        migrations.RemoveField(
            model_name='eventtranslation',
            name='price',
        ),
        migrations.RemoveField(
            model_name='eventtranslation',
            name='start_date',
        ),
        migrations.RemoveField(
            model_name='organizationtranslation',
            name='email',
        ),
        migrations.RemoveField(
            model_name='organizationtranslation',
            name='name',
        ),
        migrations.RemoveField(
            model_name='organizationtranslation',
            name='phone',
        ),
        migrations.AddField(
            model_name='event',
            name='end_date',
            field=models.DateField(blank=True, null=True, verbose_name='End Date'),
        ),
        migrations.AddField(
            model_name='event',
            name='price',
            field=models.DecimalField(decimal_places=2, default=20, max_digits=5, verbose_name='Price'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='event',
            name='start_date',
            field=models.DateField(blank=True, null=True, verbose_name='Start Date'),
        ),
        migrations.AddField(
            model_name='organization',
            name='email',
            field=models.EmailField(default=1, max_length=200, verbose_name='Email'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='organization',
            name='name',
            field=models.CharField(default=1, max_length=200, verbose_name='Name'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='organization',
            name='phone',
            field=models.CharField(max_length=20, null=True, verbose_name='Phone'),
        ),
    ]
