# Generated by Django 4.2 on 2024-04-25 16:35

from django.db import migrations, models
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('parent_resource_app', '0002_organization_id_alter_organization_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='age_group_en',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('0y', '0-1 years'), ('1y', '1-2 years'), ('2y', '2-3 years'), ('3y', '3-4 years'), ('4y', '4-5 years'), ('5y', '5-6 years'), ('6y', '6-7 years'), ('7y', '7-8 years'), ('8y', '8-9 years'), ('9y', '9-10 years'), ('10y', '10-11 years'), ('11y', '11-12 years'), ('12y', '12-13 year'), ('13+', '13 or older'), ('P', 'For Parents'), ('All', 'All ages')], max_length=25, null=True, verbose_name='Age Group'),
        ),
        migrations.AddField(
            model_name='event',
            name='age_group_es',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('0y', '0-1 years'), ('1y', '1-2 years'), ('2y', '2-3 years'), ('3y', '3-4 years'), ('4y', '4-5 years'), ('5y', '5-6 years'), ('6y', '6-7 years'), ('7y', '7-8 years'), ('8y', '8-9 years'), ('9y', '9-10 years'), ('10y', '10-11 years'), ('11y', '11-12 years'), ('12y', '12-13 year'), ('13+', '13 or older'), ('P', 'For Parents'), ('All', 'All ages')], max_length=25, null=True, verbose_name='Age Group'),
        ),
        migrations.AddField(
            model_name='event',
            name='description_en',
            field=models.TextField(max_length=200, null=True, verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='event',
            name='description_es',
            field=models.TextField(max_length=200, null=True, verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='event',
            name='service_type_en',
            field=models.CharField(choices=[('Family Fun', 'Family Fun'), ('Health and Well-being', 'Health and Well-being'), ('Benefits or Financial Aid', 'Benefits or Financial Aid')], max_length=200, null=True, verbose_name='Type of Event'),
        ),
        migrations.AddField(
            model_name='event',
            name='service_type_es',
            field=models.CharField(choices=[('Family Fun', 'Family Fun'), ('Health and Well-being', 'Health and Well-being'), ('Benefits or Financial Aid', 'Benefits or Financial Aid')], max_length=200, null=True, verbose_name='Type of Event'),
        ),
        migrations.AddField(
            model_name='event',
            name='title_en',
            field=models.CharField(max_length=200, null=True, verbose_name='Title'),
        ),
        migrations.AddField(
            model_name='event',
            name='title_es',
            field=models.CharField(max_length=200, null=True, verbose_name='Title'),
        ),
    ]
