# Generated by Django 4.2 on 2024-04-26 19:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('parent_resource_app', '0003_event_age_group_en_event_age_group_es_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='age_group_en',
        ),
        migrations.RemoveField(
            model_name='event',
            name='age_group_es',
        ),
        migrations.RemoveField(
            model_name='event',
            name='description_en',
        ),
        migrations.RemoveField(
            model_name='event',
            name='description_es',
        ),
        migrations.RemoveField(
            model_name='event',
            name='service_type_en',
        ),
        migrations.RemoveField(
            model_name='event',
            name='service_type_es',
        ),
        migrations.RemoveField(
            model_name='event',
            name='title_en',
        ),
        migrations.RemoveField(
            model_name='event',
            name='title_es',
        ),
        migrations.RemoveField(
            model_name='organization',
            name='about_en',
        ),
        migrations.RemoveField(
            model_name='organization',
            name='about_es',
        ),
    ]
