# Generated by Django 4.2 on 2024-04-08 05:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parent_resource_app', '0004_alter_event_start_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='end_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='End Date'),
        ),
        migrations.AlterField(
            model_name='event',
            name='location',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Location'),
        ),
    ]
