# Generated by Django 4.2 on 2024-04-08 17:50

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('parent_resource_app', '0005_alter_event_end_date_alter_event_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='age_group',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('0', '0-1 years'), ('1', '1-2 years'), ('2', '2-3 years'), ('3', '3-4 years'), ('4', '4-5 years'), ('5', '5-6 years'), ('6', '6-7 years'), ('7', '7-8 years'), ('8', '8-9 years'), ('9', '9-10 years'), ('10', '10-11 years'), ('11', '11-12 years'), ('12', '12-13 year'), ('13+', '13 or older'), ('P', 'For Parents'), ('All', 'All ages')], max_length=200),
        ),
    ]
