# Generated by Django 4.2 on 2024-04-08 22:06

from django.db import migrations, models
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('parent_resource_app', '0010_alter_event_age_group'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='age_group',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('0y', '0-1 years'), ('1y', '1-2 years'), ('2y', '2-3 years'), ('3y', '3-4 years'), ('4y', '4-5 years'), ('5y', '5-6 years'), ('6y', '6-7 years'), ('7y', '7-8 years'), ('8y', '8-9 years'), ('9y', '9-10 years'), ('10y', '10-11 years'), ('11y', '11-12 years'), ('12y', '12-13 year'), ('13+', '13 or older'), ('P', 'For Parents'), ('All', 'All ages')], max_length=25),
        ),
        migrations.AlterField(
            model_name='event',
            name='service_type',
            field=models.CharField(choices=[('Family Fun', 'Family Fun'), ('Health and Well-being', 'Health and Well-being'), ('Benefits or Financial Aid', 'Benefits or Financial Aid')], max_length=200, verbose_name='Type of Event'),
        ),
    ]
