# Generated by Django 4.2 on 2024-04-09 03:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parent_resource_app', '0011_alter_event_age_group_alter_event_service_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='end_date',
            field=models.DateField(blank=True, null=True, verbose_name='End Date'),
        ),
        migrations.AlterField(
            model_name='event',
            name='start_date',
            field=models.DateField(blank=True, null=True, verbose_name='Start Date'),
        ),
    ]
