# Generated by Django 4.2 on 2024-04-18 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parent_resource_app', '0014_alter_organization_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organization',
            name='email',
            field=models.EmailField(max_length=200, verbose_name='Email'),
        ),
    ]
