# Generated by Django 4.2 on 2024-04-25 06:44

from django.db import migrations, models
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('parent_resource_app', '0015_alter_organization_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='age_group',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('0y', '0-1 years'), ('1y', '1-2 years'), ('2y', '2-3 years'), ('3y', '3-4 years'), ('4y', '4-5 years'), ('5y', '5-6 years'), ('6y', '6-7 years'), ('7y', '7-8 years'), ('8y', '8-9 years'), ('9y', '9-10 years'), ('10y', '10-11 years'), ('11y', '11-12 years'), ('12y', '12-13 year'), ('13+', '13 or older'), ('P', 'For Parents'), ('All', 'All ages')], max_length=25, verbose_name='Age Group'),
        ),
        migrations.AlterField(
            model_name='event',
            name='description',
            field=models.TextField(max_length=200, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='event',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Price'),
        ),
        migrations.AlterField(
            model_name='event',
            name='title',
            field=models.CharField(max_length=200, verbose_name='Title'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='about',
            field=models.TextField(max_length=200, verbose_name='about'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='name',
            field=models.CharField(max_length=200, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='phone',
            field=models.CharField(max_length=20, null=True, verbose_name='Phone'),
        ),
    ]
