# Generated by Django 4.2 on 2024-04-25 07:24

from django.db import migrations, models
import django.db.models.deletion
import multiselectfield.db.fields
import parler.fields
import parler.models


class Migration(migrations.Migration):

    dependencies = [
        ('parent_resource_app', '0016_alter_event_age_group_alter_event_description_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='age_group',
        ),
        migrations.RemoveField(
            model_name='event',
            name='description',
        ),
        migrations.RemoveField(
            model_name='event',
            name='end_date',
        ),
        migrations.RemoveField(
            model_name='event',
            name='location',
        ),
        migrations.RemoveField(
            model_name='event',
            name='price',
        ),
        migrations.RemoveField(
            model_name='event',
            name='service_type',
        ),
        migrations.RemoveField(
            model_name='event',
            name='start_date',
        ),
        migrations.RemoveField(
            model_name='event',
            name='title',
        ),
        migrations.RemoveField(
            model_name='organization',
            name='about',
        ),
        migrations.RemoveField(
            model_name='organization',
            name='email',
        ),
        migrations.RemoveField(
            model_name='organization',
            name='name',
        ),
        migrations.RemoveField(
            model_name='organization',
            name='phone',
        ),
        migrations.CreateModel(
            name='OrganizationTranslation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language_code', models.CharField(db_index=True, max_length=15, verbose_name='Language')),
                ('name', models.CharField(max_length=200, verbose_name='Name')),
                ('email', models.EmailField(max_length=200, verbose_name='Email')),
                ('phone', models.CharField(max_length=20, null=True, verbose_name='Phone')),
                ('about', models.TextField(max_length=200, verbose_name='about')),
                ('master', parler.fields.TranslationsForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='parent_resource_app.organization')),
            ],
            options={
                'verbose_name': 'organization Translation',
                'db_table': 'parent_resource_app_organization_translation',
                'db_tablespace': '',
                'managed': True,
                'default_permissions': (),
                'unique_together': {('language_code', 'master')},
            },
            bases=(parler.models.TranslatableModel, models.Model),
        ),
        migrations.CreateModel(
            name='EventTranslation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language_code', models.CharField(db_index=True, max_length=15, verbose_name='Language')),
                ('title', models.CharField(max_length=200, verbose_name='Title')),
                ('service_type', models.CharField(choices=[('Family Fun', 'Family Fun'), ('Health and Well-being', 'Health and Well-being'), ('Benefits or Financial Aid', 'Benefits or Financial Aid')], max_length=200, verbose_name='Type of Event')),
                ('price', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Price')),
                ('description', models.TextField(max_length=200, verbose_name='Description')),
                ('age_group', multiselectfield.db.fields.MultiSelectField(choices=[('0y', '0-1 years'), ('1y', '1-2 years'), ('2y', '2-3 years'), ('3y', '3-4 years'), ('4y', '4-5 years'), ('5y', '5-6 years'), ('6y', '6-7 years'), ('7y', '7-8 years'), ('8y', '8-9 years'), ('9y', '9-10 years'), ('10y', '10-11 years'), ('11y', '11-12 years'), ('12y', '12-13 year'), ('13+', '13 or older'), ('P', 'For Parents'), ('All', 'All ages')], max_length=25, verbose_name='Age Group')),
                ('start_date', models.DateField(blank=True, null=True, verbose_name='Start Date')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='End Date')),
                ('location', models.CharField(blank=True, max_length=200, null=True, verbose_name='Location')),
                ('master', parler.fields.TranslationsForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='parent_resource_app.event')),
            ],
            options={
                'verbose_name': 'event Translation',
                'db_table': 'parent_resource_app_event_translation',
                'db_tablespace': '',
                'managed': True,
                'default_permissions': (),
                'unique_together': {('language_code', 'master')},
            },
            bases=(parler.models.TranslatableModel, models.Model),
        ),
    ]
