# Generated by Django 4.2 on 2024-04-25 07:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('parent_resource_app', '0017_remove_event_age_group_remove_event_description_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='organization',
        ),
        migrations.RemoveField(
            model_name='organization',
            name='user',
        ),
        migrations.AddField(
            model_name='eventtranslation',
            name='organization',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='parent_resource_app.organization'),
        ),
        migrations.AddField(
            model_name='organizationtranslation',
            name='user',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
