# Generated by Django 4.2 on 2024-04-25 08:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('parent_resource_app', '0018_remove_event_organization_remove_organization_user_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='eventtranslation',
            name='organization',
        ),
        migrations.AddField(
            model_name='event',
            name='organization',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='parent_resource_app.organization'),
        ),
    ]
