# Generated by Django 4.2 on 2024-04-25 08:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('parent_resource_app', '0019_remove_eventtranslation_organization_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='organizationtranslation',
            name='user',
        ),
        migrations.AddField(
            model_name='organization',
            name='user',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
